name: IEEE Student Branch at UOIT
description: IEEE Student Branch at UOIT
baseurl: '/'

# url: "http://uoitieee.ca"
permalink: /:title/
plugins: [jekyll-paginate]
paginate: 2
paginate_path: "news/page:num"

