name: IEEE Student Branch at UOIT
description: IEEE Student Branch at UOIT
baseurl: '/UOITIEEE'

# url: "http://localhost:4000"
permalink: /:title/
plugins: [jekyll-paginate]
paginate: 2
paginate_path: "news/page:num"

